// Command bench builds every program under bench/ with gc and with rustygo,
// checks that both print the same thing, and reports run time (best of -n),
// peak memory, and compile-side numbers: lines of Go, lines of emitted Rust,
// and the time cargo takes to build them.
//
//	go run ./internal/cmd/bench [-n 5] [-o docs/BENCHMARKS.md]
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/KarpelesLab/rustygo/internal/build"
	"github.com/KarpelesLab/rustygo/internal/load"
)

type measure struct {
	best time.Duration
	rss  int64 // bytes; 0 if unknown
	out  string
}

func main() {
	n := flag.Int("n", 5, "runs per binary; the fastest counts")
	outFile := flag.String("o", "", "also write the markdown report here")
	flag.Parse()

	entries, err := os.ReadDir("bench")
	check(err)
	tmp, err := os.MkdirTemp("", "rustygo-bench-")
	check(err)
	defer os.RemoveAll(tmp)
	// Warm the runtime crate so the first program's build time is its own.
	if _, err := build.RuntimeDir(); err != nil {
		check(err)
	}

	var run, comp strings.Builder
	run.WriteString("| benchmark | gc | rustygo | rustygo / gc | gc peak RSS | rustygo peak RSS |\n|---|---:|---:|---:|---:|---:|\n")
	comp.WriteString("| program | Go lines | emitted Rust lines | Rust lines per Go line | cargo build |\n|---|---:|---:|---:|---:|\n")
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		pkg := "./bench/" + name
		fmt.Fprintf(os.Stderr, "%s...\n", name)

		gcBin := filepath.Join(tmp, name+"-gc"+exeSuffix())
		cmd := exec.Command("go", "build", "-o", gcBin, pkg)
		cmd.Stderr = os.Stderr
		check(cmd.Run())

		res, err := load.Load("", pkg)
		check(err)
		rgBin := filepath.Join(tmp, name+"-rustygo"+exeSuffix())
		start := time.Now()
		check(build.Binary(res, rgBin, build.Config{}))
		buildTime := time.Since(start)
		work, err := build.WorkDir(res, build.Config{})
		check(err)
		// Interleave the runs so machine noise hits both alike.
		var gc, rg measure
		for i := 0; i < *n; i++ {
			gc = gc.merge(runOnce(gcBin))
			rg = rg.merge(runOnce(rgBin))
		}
		if rg.out != gc.out {
			fmt.Fprintf(os.Stderr, "%s: outputs differ\ngc: %q\nrustygo: %q\n", name, gc.out, rg.out)
			os.Exit(1)
		}
		fmt.Fprintf(&run, "| %s | %s | %s | %.2f× | %s | %s |\n", name, dur(gc.best), dur(rg.best),
			rg.best.Seconds()/gc.best.Seconds(), mib(gc.rss), mib(rg.rss))

		goLines := countLines(filepath.Join("bench", name), ".go")
		rustLines := countLines(filepath.Join(work, "src"), ".rs")
		fmt.Fprintf(&comp, "| %s | %d | %d | %.1f | %s |\n", name, goLines, rustLines,
			float64(rustLines)/float64(goLines), dur(buildTime))
	}

	fmt.Fprintf(os.Stderr, "compile scaling...\n")
	scale := compileScale(tmp)

	report := fmt.Sprintf(`# Benchmarks

Generated by `+"`go run ./internal/cmd/bench`"+` on %s/%s (%s, best of %d runs).
Both builds are native; gc is `+"`go build`"+` with default flags, rustygo is
`+"`cargo build --release`"+` on the emitted crate. Runs of the two
binaries are interleaved so machine noise affects them alike.

## Run time

%s
## Compilation

Emitted lines count every generated `+"`.rs`"+` file. Build time is emit +
`+"`cargo build --release`"+` with the runtime crate already compiled.

%s
## Compile-time scaling

Generated programs of the M0 subset, built from scratch (runtime crate
already compiled):

%s`, runtime.GOOS, runtime.GOARCH, runtime.Version(), *n, run.String(), comp.String(), scale)
	fmt.Print(report)
	if *outFile != "" {
		check(os.WriteFile(*outFile, []byte(report), 0o644))
	}
}

func runOnce(bin string) measure {
	cmd := exec.Command(bin)
	var out bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &out
	start := time.Now()
	check(cmd.Start())
	stop := watchRSS(cmd.Process.Pid)
	err := cmd.Wait()
	d := time.Since(start)
	rss := stop()
	check(err)
	return measure{best: d, rss: max(rss, rusagePeak(cmd.ProcessState)), out: out.String()}
}

// merge keeps the fastest time and the largest peak.
func (m measure) merge(o measure) measure {
	if m.best == 0 || o.best < m.best {
		m.best = o.best
	}
	m.rss = max(m.rss, o.rss)
	m.out = o.out
	return m
}

// countLines counts non-blank lines in the ext files under dir (or in dir
// itself, if it is a file).
func countLines(dir, ext string) int {
	n := 0
	filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || filepath.Ext(path) != ext {
			return err
		}
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			if strings.TrimSpace(sc.Text()) != "" {
				n++
			}
		}
		return nil
	})
	return n
}

func dur(d time.Duration) string {
	if d < time.Second {
		return fmt.Sprintf("%.0f ms", d.Seconds()*1000)
	}
	return fmt.Sprintf("%.2f s", d.Seconds())
}

func mib(b int64) string {
	if b == 0 {
		return "n/a"
	}
	return fmt.Sprintf("%.1f MiB", float64(b)/(1<<20))
}

func exeSuffix() string {
	if runtime.GOOS == "windows" {
		return ".exe"
	}
	return ""
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
