// Command gotest runs the Go distribution's own `test/` directory through
// rustygo and reports the pass rate.
//
//	go run ./internal/cmd/gotest [-n 4] [-o docs/GOTEST.md] [-dir $GOROOT/test]
//
// Only the tests marked `// run` are used: the rest check the gc compiler's
// diagnostics, or need a directory of files. Each one is built with gc and
// with rustygo and the two are run and compared, the same way the
// differential harness compares testdata/programs (DESIGN §12), so Go's own
// expectations files are not needed.
//
// Tests that gc itself cannot build here are skipped, not counted.
//
// `-n` builds that many tests at once, and defaults to one on purpose. cargo
// decides how many `rustc` processes a build runs with its own `jobs` setting,
// which a machine's `~/.cargo/config.toml` may set deliberately low; building
// several tests at once multiplies that number rather than sharing it. Raise it
// only if you know the machine can take it — and note that a `// run` test
// measuring time, as `chanlinear` does, is measured under whatever load the
// other workers are making.
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/KarpelesLab/rustygo/internal/build"
	"github.com/KarpelesLab/rustygo/internal/load"
)

type result struct {
	name    string
	ok      bool
	skipped bool
	reason  string
	// The two binaries, kept only for a failure that got as far as running
	// them, so that [retry] can run them again without building anything.
	gcBin, rgBin string
	timeout      time.Duration
}

func main() {
	workers := flag.Int("n", 1, "tests to build at once (see the note on -n above)")
	outFile := flag.String("o", "", "also write the markdown report here")
	dir := flag.String("dir", filepath.Join(runtime.GOROOT(), "test"), "directory of Go's own tests")
	timeout := flag.Duration("timeout", 30*time.Second, "per-program run timeout")
	list := flag.Bool("list", false, "list failing tests and their first difference")
	flag.Parse()

	files, err := runTests(*dir)
	check(err)
	if len(files) == 0 {
		fmt.Fprintf(os.Stderr, "no `// run` tests in %s\n", *dir)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "%d `// run` tests in %s\n", len(files), *dir)

	tmp, err := os.MkdirTemp("", "rustygo-gotest-")
	check(err)
	defer os.RemoveAll(tmp)

	results := make([]result, len(files))
	var wg sync.WaitGroup
	work := make(chan int)
	for w := 0; w < *workers; w++ {
		// One cache per worker: cargo locks its target directory, so
		// sharing one would serialize every build.
		cfg := build.Config{Cache: filepath.Join(tmp, fmt.Sprintf("cache%d", w))}
		wg.Add(1)
		go func(w int, cfg build.Config) {
			defer wg.Done()
			for i := range work {
				results[i] = runOne(files[i], filepath.Join(tmp, fmt.Sprintf("w%d", w)), cfg, *timeout)
				fmt.Fprint(os.Stderr, map[bool]string{true: ".", false: "x"}[results[i].ok || results[i].skipped])
			}
		}(w, cfg)
	}
	for i := range files {
		work <- i
	}
	close(work)
	wg.Wait()
	fmt.Fprintln(os.Stderr)

	// Now that nothing else is running, give each failure one more run.
	for i, r := range results {
		again := retry(r)
		if again.ok && !r.ok {
			fmt.Fprintf(os.Stderr, "%s passed on its own\n", r.name)
		}
		results[i] = again
	}

	var passed, skipped int
	var failures []result
	for _, r := range results {
		switch {
		case r.skipped:
			skipped++
		case r.ok:
			passed++
		default:
			failures = append(failures, r)
		}
	}
	counted := len(results) - skipped
	sort.Slice(failures, func(i, j int) bool { return failures[i].name < failures[j].name })

	var b strings.Builder
	fmt.Fprintf(&b, `# Go's own tests

The `+"`// run`"+` tests in the Go distribution's %s, built with gc and with
rustygo and compared on output and exit status (DESIGN §12). Tests gc itself
cannot build in this environment are skipped, not counted.

Generated by `+"`go run ./internal/cmd/gotest`"+` on %s/%s, %s.

| tests | passing | rate |
|---:|---:|---:|
| %d | %d | %.0f%% |
`, "`test/` directory", runtime.GOOS, runtime.GOARCH, runtime.Version(), counted, passed, 100*float64(passed)/float64(counted))
	if skipped > 0 {
		fmt.Fprintf(&b, "\n%d skipped.\n", skipped)
	}
	if len(failures) > 0 {
		b.WriteString("\n## Failing\n\n| test | why |\n|---|---|\n")
		for _, f := range failures {
			fmt.Fprintf(&b, "| %s | %s |\n", f.name, oneLine(f.reason))
		}
	}
	fmt.Print(b.String())
	if *outFile != "" {
		check(os.WriteFile(*outFile, []byte(b.String()), 0o644))
	}
	if *list {
		for _, f := range failures {
			fmt.Fprintf(os.Stderr, "\n=== %s\n%s\n", f.name, f.reason)
		}
	}
}

// runTests returns the files in dir whose first line marks them `// run`
// with no extra flags.
func runTests(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		first, _, _ := strings.Cut(string(data), "\n")
		if strings.TrimSpace(first) == "// run" {
			files = append(files, path)
		}
	}
	return files, nil
}

func runOne(path, work string, cfg build.Config, timeout time.Duration) result {
	name := filepath.Base(path)
	r := result{name: name}
	if err := os.MkdirAll(work, 0o755); err != nil {
		return result{name: name, skipped: true, reason: err.Error()}
	}
	exe := ""
	if runtime.GOOS == "windows" {
		exe = ".exe"
	}

	// Named after the test, because a failure's binaries outlive the worker's
	// next test.
	gcBin := filepath.Join(work, name+"-gc"+exe)
	cmd := exec.Command("go", "build", "-o", gcBin, path)
	if out, err := cmd.CombinedOutput(); err != nil {
		// gc will not build it here: not rustygo's failure to count.
		return result{name: name, skipped: true, reason: strings.TrimSpace(string(out))}
	}
	want, err := run(gcBin, timeout, false)
	if err != nil {
		return result{name: name, skipped: true, reason: "gc run: " + err.Error()}
	}

	rgBin := filepath.Join(work, name+"-rustygo"+exe)
	res, err := load.Load(filepath.Dir(path), path)
	if err == nil {
		err = build.Binary(res, rgBin, cfg)
	}
	if err != nil {
		r.reason = firstError(err.Error())
		return r
	}
	r.gcBin, r.rgBin, r.timeout = gcBin, rgBin, timeout
	got, err := run(rgBin, timeout, true)
	if err != nil {
		r.reason = "rustygo run: " + err.Error()
		return r
	}
	if diff := compare(want, got); diff != "" {
		r.reason = diff
		return r
	}
	r.ok = true
	os.Remove(gcBin)
	os.Remove(rgBin)
	return r
}

// retry runs a failed test's two binaries again, alone.
//
// Several of Go's tests measure time — `chanlinear` asserts that dequeuing
// from a channel stays linear by comparing two durations — and the first run
// happened while every other worker was compiling. A failure that got as far
// as running is therefore given one more go with the machine to itself, and
// only a difference that survives that is reported.
func retry(r result) result {
	if r.ok || r.skipped || r.gcBin == "" {
		return r
	}
	want, err := run(r.gcBin, r.timeout, false)
	if err != nil {
		return r
	}
	got, err := run(r.rgBin, r.timeout, true)
	if err != nil {
		return r
	}
	if diff := compare(want, got); diff != "" {
		r.reason = diff
		return r
	}
	r.ok = true
	r.reason = ""
	return r
}

type outcome struct {
	stdout, stderr string
	exit           int
}

// run executes a test binary; a rustygo-built one runs under a memory cap
// (build.TestCommand).
func run(bin string, timeout time.Duration, limit bool) (outcome, error) {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, bin)
	if limit {
		cmd = build.TestCommand(ctx, bin)
	}
	// Some of Go's tests print a great deal; keep only the first part, the
	// same amount from both compilers.
	stdout, stderr := &capped{}, &capped{}
	cmd.Stdout, cmd.Stderr = stdout, stderr
	err := cmd.Run()
	if ctx.Err() != nil {
		return outcome{}, fmt.Errorf("timed out after %v", timeout)
	}
	exit := 0
	var ee *exec.ExitError
	if errors.As(err, &ee) {
		exit = ee.ExitCode()
	} else if err != nil {
		return outcome{}, err
	}
	return outcome{stdout.String(), normalize(stderr.String()), exit}, nil
}

// capped collects at most maxOutput bytes and drops the rest.
type capped struct {
	buf bytes.Buffer
}

const maxOutput = 1 << 20

func (c *capped) Write(p []byte) (int, error) {
	if room := maxOutput - c.buf.Len(); room > 0 {
		c.buf.Write(p[:min(room, len(p))])
	}
	return len(p), nil
}

func (c *capped) String() string { return c.buf.String() }

// normalize drops gc's signal line and goroutine traces, as the differential
// harness does.
func normalize(s string) string {
	for _, marker := range []string{"\n[signal ", "\n\ngoroutine "} {
		if i := strings.Index(s, marker); i >= 0 {
			s = s[:i+1]
		}
	}
	return s
}

func compare(want, got outcome) string {
	switch {
	case want.exit != got.exit:
		return fmt.Sprintf("exit status: gc %d, rustygo %d", want.exit, got.exit)
	case want.stdout != got.stdout:
		return "stdout: gc " + quote(want.stdout) + ", rustygo " + quote(got.stdout)
	case want.stderr != got.stderr:
		return "stderr: gc " + quote(want.stderr) + ", rustygo " + quote(got.stderr)
	}
	return ""
}

func quote(s string) string {
	s = strings.TrimSpace(s)
	if len(s) > 60 {
		s = s[:60] + "…"
	}
	return fmt.Sprintf("%q", s)
}

// firstError keeps the first line of a build failure, which is the one that
// says what is unsupported.
func firstError(s string) string {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "cargo build failed") {
			continue
		}
		if i := strings.LastIndex(line, "/"); i >= 0 {
			line = line[i+1:]
		}
		return line
	}
	return oneLine(s)
}

func oneLine(s string) string {
	s = strings.ReplaceAll(strings.TrimSpace(s), "\n", " · ")
	s = strings.ReplaceAll(s, "|", "\\|")
	if len(s) > 150 {
		s = s[:150] + "…"
	}
	return s
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
